#lang racket
;Modificadores creados para pacientes.
(define (modificaIDPaciente Pacientes Id)
  (createPaciente Id
            (obtenerRunPaciente Pacientes)
            (obtenerEmailPaciente Pacientes)
            (obtenerNombrePaciente Pacientes)
            (obtenerApellidoPaciente Pacientes)
            (obtenerFechaNacimientoPaciente Pacientes)
  )
)
(define (modificaRunPaciente Pacientes run)
  (createPaciente (obtenerIDPaciente Pacientes) 
            run
            (obtenerEmailPaciente Pacientes)
            (obtenerNombrePaciente Pacientes)
            (obtenerApellidoPaciente Pacientes)
            (obtenerFechaNacimientoPaciente Pacientes)
  )
)
(define (modificaEmailPaciente Pacientes email)
  (createPaciente (obtenerIDPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            email
            (obtenerNombrePaciente Pacientes)
            (obtenerApellidoPaciente Pacientes)
            (obtenerFechaNacimientoPaciente Pacientes)
  )
)

(define (modificaNombrePaciente Pacientes nombre)
  (createPaciente (obtenerIDPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            nombre
            (obtenerApellidoPaciente Pacientes)
            (obtenerFechaNacimientoPaciente Pacientes)
  )
)
(define (modificaApellidoPaciente Pacientes apellido)
  (createPaciente (obtenerIDPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            (obtenerNombrePaciente Pacientes)
            apellido
            (obtenerFechaNacimientoPaciente Pacientes)
  )
)
(define (modificaFechaNacimientoPaciente Pacientes fechaNac)
  (createPaciente (obtenerIDPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            (obtenerRunPaciente Pacientes)
            (obtenerNombrePaciente Pacientes)
            (obtenerApellidoPaciente Pacientes)
            fechaNac
  )
)

;Modificadores creados para doctores.
(define (modificaIDDoctor Doctores Id)
  (createDoctor Id
            (obtenerRutDoctor Doctores)
            (obtenerEmailDoctor Doctores)
            (obtenerNombreDoctor Doctores)
            (obtenerApellidoDoctor Doctores)
            (obtenerEspecialidadDoctor Doctores)
  )
)
(define (modificaRutDoctor Doctores run)
  (createDoctor (obtenerIDDoctor Doctores)
            run
            (obtenerEmailDoctor Doctores)
            (obtenerNombreDoctor Doctores)
            (obtenerApellidoDoctor Doctores)
            (obtenerEspecialidadDoctor Doctores)
  )
)
(define (modificaEmailDoctor Doctores email)
  (createDoctor (obtenerIDDoctor Doctores)
            (obtenerRutDoctor Doctores)
            email
            (obtenerNombreDoctor Doctores)
            (obtenerApellidoDoctor Doctores)
            (obtenerEspecialidadDoctor Doctores)
  )
)
(define (modificaNombreDoctor Doctores nombre)
  (createDoctor (obtenerIDDoctor Doctores)
            (obtenerRutDoctor Doctores)
            (obtenerEmailDoctor Doctores)
            nombre
            (obtenerApellidoDoctor Doctores)
            (obtenerEspecialidadDoctor Doctores)
  )
)
(define (modificaApellidoDoctor Doctores apellido)
  (createDoctor (obtenerIDDoctor Doctores)
            (obtenerRutDoctor Doctores)
            (obtenerEmailDoctor Doctores)
            (obtenerNombreDoctor Doctores)
            apellido
            (obtenerEspecialidadDoctor Doctores)
  )
)
(define (modificaEspecialidadDoctor Doctores especialidad)
  (createDoctor (obtenerIDDoctor Doctores)
            (obtenerRutDoctor Doctores)
            (obtenerEmailDoctor Doctores)
            (obtenerNombreDoctor Doctores)
            (obtenerApellidoDoctor Doctores)
            especialidad
  )
)

;Modificadores creados para diagnosticos.
(define (modificaIDDiagnostico Diagnosticos Id)
  (createDiagnostico Id
            (obtenerDescripcionDiagnostico Diagnosticos)
            (obtenerNivelGravedadDiagnostico Diagnosticos)
  )
)
(define (modificaDescripcionDiagnostico Diagnosticos descripcionDiagnostico)
  (createDiagnostico (obtenerIDDiagnostico Diagnosticos)
            descripcionDiagnostico
            (obtenerNivelGravedadDiagnostico Diagnosticos)
  )
)
(define (modificaNivelGravedadDiagnostico Diagnosticos nivelGravedad)
  (createDiagnostico (obtenerIDDiagnostico Diagnosticos)
            (obtenerDescripcionDiagnostico Diagnosticos)
            nivelGravedad
  )
)

;Modificadores creados para tratamientos.
(define (modificaIDTratamiento Tratamientos Id)
 (createTratamiento Id
            (obtenerNombreTratamiento Tratamientos)
            (obtenerDescripcionTratamiento Tratamientos)
            (obtenerNivelRiesgoTratamiento Tratamientos)
  )
)
(define (modificaNombreTratamiento Tratamientos nombre)
  (createTratamiento (obtenerIDTratamiento Tratamientos)
            nombre
            (obtenerDescripcionTratamiento Tratamientos)
            (obtenerNivelRiesgoTratamiento Tratamientos)
  )
)
(define (modificadescripcionTratamiento Tratamientos descripcion)
  (createTratamiento (obtenerIDTratamiento Tratamientos)
            (obtenerNombreTratamiento Tratamientos)
            descripcion
            (obtenerNivelRiesgoTratamiento Tratamientos)
  )
)
(define (modificaNivelRiesgoTratamiento Tratamientos nivelRiesgo)
  (createTratamiento (obtenerIDTratamiento Tratamientos)
            (obtenerNombreTratamiento Tratamientos)
            (obtenerDescripcionTratamiento Tratamientos)
            nivelRiesgo
  )
)

;Modificadores creados para la relacion diagnosticosPacientes.
(define (modificaIDDiagnosticoPaciente DiagnosticosPacientes Id)
  (createDiagnosticoPaciente Id
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaIdPacienteDiagnosticoPaciente DiagnosticosPacientes IdPaciente)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            IdPaciente
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes IdDiagnostico)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            IdDiagnostico
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes FechaDiagnostico)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            FechaDiagnostico
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaIdDoctorDiagnosticoPaciente DiagnosticosPacientes IdDoctor)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            IdDoctor
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes EstadoDiagnostico)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            EstadoDiagnostico
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaFechaAltaDiagnosticoPaciente DiagnosticosPacientes FechaAlta)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            FechaAlta
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaIdDoctorAltaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes IdDoctorAlta)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            IdDoctorAlta
            (obtenerDetalleAltaDiagnosticoPaciente DiagnosticosPacientes)
  )
)
(define (modificaDetalleAltaDiagnosticoPaciente DiagnosticosPacientes DetalleAlta)
  (createDiagnosticoPaciente (obtenerIDDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdPacienteDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerEstadoDiagnosticoDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerFechaAltaDiagnosticoPaciente DiagnosticosPacientes)
            (obtenerIdDoctorAltaDiagnosticoPaciente DiagnosticosPacientes)
            DetalleAlta
  )
)

;Modificadores creados para la relacion TratamientosDiagnosticos.
(define (modificaIdDiagnosticoTratamientoDiagnostico TratamientosDiagnosticos idDiagnostico)
  (createTratamientoDiagnostico idDiagnostico
            (obtenerIdTratamientoTratamientoDiagnostico TratamientosDiagnosticos)
  )
)
(define (modificaIdTratamientoTratamientoDiagnostico TratamientosDiagnosticos idTratamiento)
  (createTratamientoDiagnostico (obtenerIdDiagnosticoTratamientoDiagnostico TratamientosDiagnosticos)
            idTratamiento
  )
)

;Modificadores creados para la relacion TratamientosDiagnosticosPacientes.
(define (modificaIDTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac Id)
  (createTratamientoDiagnosticoPaciente Id
            (obtenerIdTratamientoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdDoctorTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerFechaInicioTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerDuracionDiasTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerResultadoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
  )
)
(define (modificaIDTratamientoTratamietoDiagnosticoPaciente TratamientosDiagnosticosPac IdTratamiento)
  (createTratamientoDiagnosticoPaciente (obtenerIdDiagnosticoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            IdTratamiento
            (obtenerIdDoctorTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerFechaInicioTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerDuracionDiasTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerResultadoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
  )
)
(define (modificaIdDoctorTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac IdDoctor)
  (createTratamientoDiagnosticoPaciente (obtenerIdDiagnosticoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdTratamientoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            IdDoctor
            (obtenerFechaInicioTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerDuracionDiasTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerResultadoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
  )
)
(define (modificaFechaInicioTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac FechaInicio)
  (createTratamientoDiagnosticoPaciente (obtenerIdDiagnosticoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdTratamientoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdDoctorTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            FechaInicio
            (obtenerDuracionDiasTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerResultadoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
  )
)
(define (modificaDuracionDiasTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac DuracionDias)
  (createTratamientoDiagnosticoPaciente (obtenerIdDiagnosticoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdTratamientoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdDoctorTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerFechaInicioTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            DuracionDias
            (obtenerResultadoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
  )
)
(define (modificaResultadoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac Resultado)
  (createTratamientoDiagnosticoPaciente (obtenerIdDiagnosticoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdTratamientoTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerIdDoctorTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerFechaInicioTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            (obtenerDuracionDiasTratamientoDiagnosticoPaciente TratamientosDiagnosticosPac)
            Resultado
  )
)
